
export const Studentdata=[

    {
        "id":1,
        "name":"Sanjay",
        "email":"sanjay@gmail.com",
        "exp":2,
        "regNo":876817114001
    },
    {
        "id":2,
        "name":"Mathi",
        "email":"mathi@gmail.com",
        "exp":1,
        "regNo":876817114002
    },
    {
        "id":3,
        "name":"Thillai",
        "email":"thillai@gmail.com",
        "exp":3,
        "regNo":876817114003
    },
    {
        "id":4,
        "name":"Siranjeevi",
        "email":"siran@gmail.com",
        "exp":1,
        "regNo":876817114004
    },
    {
        "id":5,
        "name":"Ragul",
        "email":"ragul@gmail.com",
        "exp":2,
        "regNo":876817114005
    },
    {
        "id":6,
        "name":"Sanakkiyan",
        "email":"thamu@gmail.com",
        "exp":1,
        "regNo":876817114006
    },
    {
        "id":7,
        "name":"Tamil",
        "email":"tamil@gmail.com",
        "exp":3,
        "regNo":876817114007
    },
    {
        "id":8,
        "name":"Dhinesh",
        "email":"dhinesh@gmail.com",
        "exp":5,
        "regNo":876817114008
    },
    {
        "id":"9",
        "name":"Prabanjan",
        "email":"prabanjan@gmail.com",
        "exp":2,
        "regNo":87681711409
    }
]   

export const TeacherData=[
    {
        "name":"Kalai",
        "dept":"Mech",
        "id":"100",
        "email":"kalai@gmail",
        "phNo":"8765476543",
        "exp":"7"
    },
    {
        "name":"Rajadurai",
        "dept":"Mech",
        "id":"101",
        "email":"Raj@gmail",
        "phNo":"9807434562",
        "exp":"6"
    },
    {
        "name":"Ramya",
        "dept":"Maths",
        "id":"102",
        "email":"ramya@gmail",
        "phNo":"9123434562",
        "exp":"14"
    },
    {
        "name":"Usha",
        "dept":"Maths",
        "id":"103",
        "email":"usha@gmail",
        "phNo":"8765434562",
        "exp":"10"
    },
    {
        "name":"ThangaBalu",
        "dept":"Mech",
        "id":"104",
        "email":"gold@gmail",
        "phNo":"8765434562",
        "exp":"2"
    },
    {
        "name":"Aravind",
        "dept":"Mech",
        "id":"105",
        "email":"aravind@gmail",
        "phNo":"8765434562",
        "exp":"3"
    }
]